sudo: required

language: go

jdk:
  - openjdk8

go:
  - "1.13"

os:
  - linux

# Just because it has java8 pre-installed.
osx_image: xcode9.3

addons:
  homebrew:
    packages:
    - wget
    - unzip
  apt:
    packages:
    - wget
    - unzip
    # - openjdk-8-jdk

before_install:
  # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install remove --purge openjdk-*-jdk -y && sudo apt install openjdk-8-jdk -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source .travis/download-sdk-tools-linux; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source .travis/download-sdk-tools-darwin; fi
  # - source .travis/install-sdk-ndk

install:
  - java --version
  # - sudo apt remove openjdk-11-jdk -y
  - java --version
  - echo "Getting deps"
  - source .travis/install-sdk-ndk
  - go get -d ./...
  - echo "Installing gomobile"
  - go get golang.org/x/mobile/cmd/gomobile
  - go install golang.org/x/mobile/cmd/gomobile
  - gomobile init
  - echo "Show Environment"
  - export

script:
  - echo "Building"
  - export
  - ls $ANDROID_HOME/ndk-bundle
  - ls $ANDROID_NDK_HOME
  # Make android on linux.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make android && ls -l build; fi
  # Make both android and ios on osx.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make && ls -l build; fi
  - tar -cvzf /tmp/files.tar.gz ./
  - mv /tmp/files.tar.gz ./
  
deploy:
  provider: releases
  api_key: "$API_KEY"
  file: "files.tar.gz"
  skip_cleanup: true
  draft: true

